(SELECT CITY, LENGTH(CITY) AS name
 FROM STATION
 ORDER BY LENGTH(CITY) ASC, CITY ASC
 LIMIT 1)
UNION
(SELECT CITY, LENGTH(CITY) AS name
 FROM STATION
 ORDER BY LENGTH(CITY) DESC, CITY ASC
 LIMIT 1);
